//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accessories {
            get {
                object obj = ResourceManager.GetObject("accessories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Acer_Aspire_C24_1700_UA91_AIO_Desktop {
            get {
                object obj = ResourceManager.GetObject("Acer Aspire C24-1700-UA91 AIO Desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Acer_V246HQL___LED_monitor___Full_HD__1080p_ {
            get {
                object obj = ResourceManager.GetObject("Acer V246HQL - LED monitor - Full HD (1080p)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_5_5600X_6_core {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 5 5600X 6-core", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_5_5600X_6_core1 {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 5 5600X 6-core1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_7_5800X_8_core {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 7 5800X 8-core", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_7_5800X_8_core1 {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 7 5800X 8-core1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_9_5900X_12_core {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 9 5900X 12-core", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_9_5900X_12_core1 {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 9 5900X 12-core1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AMD_Ryzen_9_5900X_12_core2 {
            get {
                object obj = ResourceManager.GetObject("AMD Ryzen 9 5900X 12-core2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Apple_iMac_21_5in_2_7GHz_Core_i5 {
            get {
                object obj = ResourceManager.GetObject("Apple iMac 21.5in 2.7GHz Core i5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ARVICKA {
            get {
                object obj = ResourceManager.GetObject("ARVICKA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_Prime_B550_PLUS {
            get {
                object obj = ResourceManager.GetObject("ASUS Prime B550-PLUS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_Prime_Z690_P_WiFi_D4 {
            get {
                object obj = ResourceManager.GetObject("ASUS Prime Z690-P WiFi D4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_ROG_Strix_B550_F_Gaming {
            get {
                object obj = ResourceManager.GetObject("ASUS ROG Strix B550-F Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_ROG_Zephyrus_M16_GU603ZM_Core_i7__12700H_RTX_3060 {
            get {
                object obj = ResourceManager.GetObject("ASUS ROG Zephyrus M16 GU603ZM Core i7 -12700H RTX 3060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_ROG_Zephyrus_M16_GU603ZM_Core_i7__12700H_RTX_30601 {
            get {
                object obj = ResourceManager.GetObject("ASUS ROG Zephyrus M16 GU603ZM Core i7 -12700H RTX 30601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ASUS_ROG_Zephyrus_M16_GU603ZM_Core_i7__12700H_RTX_30602 {
            get {
                object obj = ResourceManager.GetObject("ASUS ROG Zephyrus M16 GU603ZM Core i7 -12700H RTX 30602", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap basket_cart_icon_27 {
            get {
                object obj = ResourceManager.GetObject("basket-cart-icon-27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cherry_Stream_Keyboard_TKL_Wired_USB {
            get {
                object obj = ResourceManager.GetObject("Cherry Stream Keyboard TKL Wired USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cherry_Stream_Keyboard_Wired_USB {
            get {
                object obj = ResourceManager.GetObject("Cherry Stream Keyboard Wired USB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Corsair_K70_PRO_MINI_WIRELESS_RGB_Gaming {
            get {
                object obj = ResourceManager.GetObject("Corsair K70 PRO MINI WIRELESS RGB Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Corsair_Vengeance_RAM_64GB_DDR4 {
            get {
                object obj = ResourceManager.GetObject("Corsair Vengeance RAM 64GB DDR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crucial_RAM_32GB_DDR4 {
            get {
                object obj = ResourceManager.GetObject("Crucial RAM 32GB DDR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crucial_RAM_64GB_Kit__2x32GB__DDR5 {
            get {
                object obj = ResourceManager.GetObject("Crucial RAM 64GB Kit (2x32GB) DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Crucial_RAM_8GB_DDR5 {
            get {
                object obj = ResourceManager.GetObject("Crucial RAM 8GB DDR5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap custom {
            get {
                object obj = ResourceManager.GetObject("custom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dell_Desktop_Computer_Package_Compatible_with_Dell_Optiplex_7010_Intel_Quad_Core_i5_3_2GHz__8GB_Ram__500GB_HDD__19_inch_LCD__DVD__WiFi__Keyboard__Mouse__Windows_10_Pro__Renewed_ {
            get {
                object obj = ResourceManager.GetObject("Dell Desktop Computer Package Compatible with Dell Optiplex 7010 Intel Quad Core " +
                        "i5 3.2GHz, 8GB Ram, 500GB HDD, 19-inch LCD, DVD, WiFi, Keyboard, Mouse, Windows " +
                        "10 Pro (Renewed)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dell_P2422H___LED_monitor___Full_HD__1080p_ {
            get {
                object obj = ResourceManager.GetObject("Dell P2422H - LED monitor - Full HD (1080p)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeLUX_Seeker_Wireless {
            get {
                object obj = ResourceManager.GetObject("DeLUX Seeker Wireless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit11 {
            get {
                object obj = ResourceManager.GetObject("Exit11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fanxiang_S201_256GB_M_2_SSD_2280 {
            get {
                object obj = ResourceManager.GetObject("fanxiang S201 256GB M.2 SSD 2280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FENISIO_Wired_Mouse {
            get {
                object obj = ResourceManager.GetObject("FENISIO Wired Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hardware {
            get {
                object obj = ResourceManager.GetObject("hardware", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Holkonbe_Ergonomic_Vertical_Mouse {
            get {
                object obj = ResourceManager.GetObject("Holkonbe Ergonomic Vertical Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HP_All_in_One_Desktop_Computer {
            get {
                object obj = ResourceManager.GetObject("HP All-in-One Desktop Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HP_Chromebase_21_5 {
            get {
                object obj = ResourceManager.GetObject("HP Chromebase 21.5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HP_Elite_Desktop_PC_Computer {
            get {
                object obj = ResourceManager.GetObject("HP Elite Desktop PC Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HP_Pavilion___Intel_Core_i5 {
            get {
                object obj = ResourceManager.GetObject("HP Pavilion - Intel Core i5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HUAWEI_MateBook_E__2022__Intel_Core_i3_11Gen_2_in_1_2_5K {
            get {
                object obj = ResourceManager.GetObject("HUAWEI MateBook E (2022) Intel Core i3 11Gen 2-in-1 2.5K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Core_i5_13600K_Desktop_Processor {
            get {
                object obj = ResourceManager.GetObject("Intel Core i5-13600K Desktop Processor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Core_i7_12700KF_Desktop {
            get {
                object obj = ResourceManager.GetObject("Intel Core i7-12700KF Desktop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Core_i9_13900K_Desktop_Processor {
            get {
                object obj = ResourceManager.GetObject("Intel Core i9-13900K Desktop Processor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Intel_Core_i9_13900K_Desktop_Processor1 {
            get {
                object obj = ResourceManager.GetObject("Intel Core i9-13900K Desktop Processor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Kids_Headphones_with_Microphone {
            get {
                object obj = ResourceManager.GetObject("Kids Headphones with Microphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KOORUI_24_Inch_Computer_Monitor__FHD {
            get {
                object obj = ResourceManager.GetObject("KOORUI 24 Inch Computer Monitor -FHD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laptops {
            get {
                object obj = ResourceManager.GetObject("laptops", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lenovo_IdeaCentre_AIO_3_2022___All_in_One_Desktop___24_FHD___HD_Camera___Win_11_8GB_Memory___1TB___256GB_Storage___AMD_Ryzen_3_5425U___Black__ {
            get {
                object obj = ResourceManager.GetObject("Lenovo IdeaCentre AIO 3-2022 - All-in-One Desktop - 24 FHD - HD Camera - Win 11-8" +
                        "GB Memory - 1TB + 256GB Storage - AMD Ryzen 3 5425U - Black -", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lenovo_IdeaPad_3___Intel_Core_i7 {
            get {
                object obj = ResourceManager.GetObject("Lenovo IdeaPad 3 - Intel Core i7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lenovo_ThinkVision_T24i_20___LED_monitor___Full_HD__1080p_ {
            get {
                object obj = ResourceManager.GetObject("Lenovo ThinkVision T24i-20 - LED monitor - Full HD (1080p)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lenovo_ThinkVision_T24i_20___LED_monitor___Full_HD__1080p_1 {
            get {
                object obj = ResourceManager.GetObject("Lenovo ThinkVision T24i-20 - LED monitor - Full HD (1080p)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lenovo_V14_ADA_AMD_Ryzen_3_3250u {
            get {
                object obj = ResourceManager.GetObject("Lenovo V14-ADA AMD Ryzen 3 3250u", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LG_FHD_32_Inch_Computer_Monitor_32ML600M_B {
            get {
                object obj = ResourceManager.GetObject("LG FHD 32-Inch Computer Monitor 32ML600M-B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LG_Ultra_Lightweight_Intel_Ci7 {
            get {
                object obj = ResourceManager.GetObject("LG Ultra-Lightweight Intel Ci7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line___Copy {
            get {
                object obj = ResourceManager.GetObject("line - Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line1 {
            get {
                object obj = ResourceManager.GetObject("line1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logitech_S120 {
            get {
                object obj = ResourceManager.GetObject("Logitech S120", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MAXSUN_GEFORCE_GT_1030 {
            get {
                object obj = ResourceManager.GetObject("MAXSUN GEFORCE GT 1030", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MAXSUN_GEFORCE_GT_10301 {
            get {
                object obj = ResourceManager.GetObject("MAXSUN GEFORCE GT 10301", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Microsoft_Natural {
            get {
                object obj = ResourceManager.GetObject("Microsoft Natural", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Microsoft_Office_Home___Student_2021 {
            get {
                object obj = ResourceManager.GetObject("Microsoft Office Home & Student 2021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mo {
            get {
                object obj = ResourceManager.GetObject("mo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap monitor {
            get {
                object obj = ResourceManager.GetObject("monitor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_B550M_PRO_VDH_WiFi_ProSeries {
            get {
                object obj = ResourceManager.GetObject("MSI B550M PRO-VDH WiFi ProSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_Gaming_AMD_Radeon_RX_6500_XT {
            get {
                object obj = ResourceManager.GetObject("MSI Gaming AMD Radeon RX 6500 XT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_Gaming_AMD_Radeon_RX_6500_XT1 {
            get {
                object obj = ResourceManager.GetObject("MSI Gaming AMD Radeon RX 6500 XT1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_Gaming_GeForce_RTX_2060 {
            get {
                object obj = ResourceManager.GetObject("MSI Gaming GeForce RTX 2060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_MPG_B550_Gaming_Plus_Gaming {
            get {
                object obj = ResourceManager.GetObject("MSI MPG B550 Gaming Plus Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MSI_PRO_Z690_A_ProSeries {
            get {
                object obj = ResourceManager.GetObject("MSI PRO Z690-A ProSeries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OneOdio_Bluetooth_Over_Ear_Headphones_Wireless_Wired {
            get {
                object obj = ResourceManager.GetObject("OneOdio Bluetooth Over Ear Headphones Wireless.Wired", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap orange_line {
            get {
                object obj = ResourceManager.GetObject("orange line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc {
            get {
                object obj = ResourceManager.GetObject("pc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_computer_logo_with_monitor_and_cpu_symbol_image_289774 {
            get {
                object obj = ResourceManager.GetObject("pngtree-computer-logo-with-monitor-and-cpu-symbol-image_289774", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Fighter_AMD_Radeon_RX_6600 {
            get {
                object obj = ResourceManager.GetObject("PowerColor Fighter AMD Radeon RX 6600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerColor_Hellhound_AMD_Radeon_RX_6600 {
            get {
                object obj = ResourceManager.GetObject("PowerColor Hellhound AMD Radeon RX 6600", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Redragon_S101_Wired_Gaming {
            get {
                object obj = ResourceManager.GetObject("Redragon S101 Wired Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROCCAT_Vulcan_Pro_Tactile_Optical_PC_Gaming {
            get {
                object obj = ResourceManager.GetObject("ROCCAT Vulcan Pro Tactile Optical PC Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SAMSUNG_970_EVO_Plus_SSD_2TB_NVMe_M_2 {
            get {
                object obj = ResourceManager.GetObject("SAMSUNG 970 EVO Plus SSD 2TB NVMe M.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SanDisk_Professional_12TB_G_DRIVE_PRO {
            get {
                object obj = ResourceManager.GetObject("SanDisk Professional 12TB G-DRIVE PRO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Seagate_BarraCuda_8TB_Internal_Hard_Drive {
            get {
                object obj = ResourceManager.GetObject("Seagate BarraCuda 8TB Internal Hard Drive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shopping_cart {
            get {
                object obj = ResourceManager.GetObject("shopping-cart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shopping_cart1 {
            get {
                object obj = ResourceManager.GetObject("shopping-cart1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Silent_Sound_System_Silent_Disco_3 {
            get {
                object obj = ResourceManager.GetObject("Silent Sound System Silent Disco 3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap software {
            get {
                object obj = ResourceManager.GetObject("software", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SOULION_R40 {
            get {
                object obj = ResourceManager.GetObject("SOULION R40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storage {
            get {
                object obj = ResourceManager.GetObject("storage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TEAMGROUP_Elite_DDR3L_8GB_Single {
            get {
                object obj = ResourceManager.GetObject("TEAMGROUP Elite DDR3L 8GB Single", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TEAMGROUP_Elite_DDR4_16GB {
            get {
                object obj = ResourceManager.GetObject("TEAMGROUP Elite DDR4 16GB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TECKNET_Wired_Mouse {
            get {
                object obj = ResourceManager.GetObject("TECKNET Wired Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TECKNET_Wireless_Mouse {
            get {
                object obj = ResourceManager.GetObject("TECKNET Wireless Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user {
            get {
                object obj = ResourceManager.GetObject("user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Verbatim_Wired_USB_Computer_Mouse {
            get {
                object obj = ResourceManager.GetObject("Verbatim Wired USB Computer Mouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WD_BLACK_1TB_SN850X_NVMe_Internal_Gaming {
            get {
                object obj = ResourceManager.GetObject("WD_BLACK 1TB SN850X NVMe Internal Gaming", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Western_Digital_8TB_WD_Blue_PC_Internal_Hard_Drive_HDD {
            get {
                object obj = ResourceManager.GetObject("Western Digital 8TB WD Blue PC Internal Hard Drive HDD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Windows_11_Home {
            get {
                object obj = ResourceManager.GetObject("Windows 11 Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZOTAC_Gaming_GeForce_RTX_3060 {
            get {
                object obj = ResourceManager.GetObject("ZOTAC Gaming GeForce RTX 3060", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
